/**
 * Vue I18n config loaded by `@nuxtjs/i18n` (configured via `nuxt.config.ts`).
 *
 * Pre-merged messages live in `i18n/messages/<locale>.json` (generated by
 * `pnpm i18n:build`). This file auto-loads every JSON in that directory so
 * adding a new language file "just works" without touching this config.
 *
 * Consumers that extend this Nuxt layer inherit these messages; their own
 * translations are merged on top by `@nuxtjs/i18n`.
 */
const files = import.meta.glob('./i18n/messages/*.json', { eager: true, import: 'default' })

const messages: Record<string, unknown> = {}
for (const [ filepath, data ] of Object.entries(files)) {
  const code = filepath.split('/').pop()!.replace('.json', '')
  messages[code] = data
}

export default defineI18nConfig(() => ({ messages }))
